grafana:
  enabled: false
coreDns:
  enabled: false
kubeControllerManager:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false
alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    scrapeInterval: "5s"
    scrapeTimeout: "4s"
    enableRemoteWriteReceiver: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
