{
 "title": "Pizzify",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Orders Arrived",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(order_created_total[$__range])))"
    }
   ]
  },
  {
   "title": "Fleet 1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil((sum(increase(booking_total{fleet=\"1\"}[$__range])) * 100 ) / sum(increase(order_created_total[$__range])))"
    }
   ]
  },
  {
   "title": "Fleet 2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil((sum(increase(booking_total{fleet=\"2\"}[$__range])) * 100 ) / sum(increase(order_created_total[$__range])))"
    }
   ]
  },
  {
   "title": "Fleet 3",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil((sum(increase(booking_total{fleet=\"3\"}[$__range])) * 100 ) / sum(increase(order_created_total[$__range])))"
    }
   ]
  },
  {
   "title": "Winner Selection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "operation": "winner_selection", "service": "job" }
   ]
  }
 ]
}